### ISSUE TITLE
Roller Coaster

### ISSUE THREAD

**Issue by DrSnowPengu** [TheClowner/ccRides-Support#25]
**Describe the feature you'd like with as much detail as possible**
Hello, I would like to request a feature that allow us to setup roller coaster rides.

**What is a roller coaster?**
An amusement park attraction that consists of a light railroad track with many tight turns and steep slopes, on which people ride in small fast open cars.

**Roller Coaster Image**
![icon-118-e1532007331111](https://user-images.githubusercontent.com/22732378/107871495-2e78e700-6e70-11eb-8760-0e9c86f82906.jpg)

**Comment by TheClowner** [comment]
Roller coasters are a bit outside the scope of ccRides, especially since I'd want to make sure you can build coaster pathing completely from scratch - and thats not an easy task. 

I do plan to, one day, create a separate plugin for roller coasters - I just don't feel I can do them justice within ccRides.
