### ISSUE TITLE
Use Marker tag on Armor Stands

### ISSUE THREAD

**Issue by qixils** [TheClowner/ccRides-Support#35]
The Armor Stands that compose rides don't seem to have the the Marker tag set, causing the hundreds of armor stands to waste a lot of ticking on a lot of nothing. On our server, we are seeing upwards of 8% of the tick being spent on armor stands on the world which uses ccRides. From my understanding, Armor Stands with Marker set to true effectively have no hitbox and skip a lot of ticking related to entity/block collisions which reduces lag.

Bonus points for setting the NBT tag `Paper.CanTickOverride` to `true` to disable all ticking in [Paper](https://github.com/PaperMC/Paper/) :P

**Comment by TheClowner** [comment]
Sadly the marker stands do have a bug that causes them to stop rendering when you look upwards, which is why they're not set to do that by default. I will add a couple of config options that will let you set them as markers in the next update.

https://bugs.mojang.com/browse/MC-98146?attachmentViewMode=list

And I'll disable ticking on paper too. That one's easy :P

**Comment by TheClowner** [comment]
Added this in v1.6.6 https://www.spigotmc.org/resources/ccrides-%C2%BB-working-theme-park-flat-rides-%C2%BB-1-8-x-to-1-17-%C2%BB.80364/update?update=408311

**Comment by qixils** [comment]
thank you :)
